import { inngest } from "../client.js";
import { helpAgent } from "../../ai/helpreply.js";
import { Help } from "../../models/help.model.js";
import { User } from "../../models/user.model.js";
import { sendMail } from "../../utils/sendmail.js";

export const helpAiProcess = inngest.createFunction(
  { id: "help/aiprocess", retries: 2 },
  { event: "aiprocess" },
  async ({ event, step }) => {
    try {
      const { queryid, userid, query } = event.data;
      console.log("function is run")

      // Step 1: Generate AI Answer
      const generateAnswer = await step.run("generateAnswer", async () => {
        const response = await helpAgent({ userid, query });

        if (response === "NO" || response?.text === "NO") {
          return null; // no answer generated
        }

        return response;
      });

      if (!generateAnswer) {
        return "No answer generated by AI";
      }

      // Step 2: Send answer via Email
      await step.run("sendAnswerInMail", async () => {
        const user = await User.findById(userid);

        await sendMail({
          to: user.email,
          subject: generateAnswer.subject || "AI Help Response",
          text: generateAnswer.text,
        });
      });

      // Step 3: Update DB
      await step.run("updateDB", async () => {
        const help = await Help.findById(queryid);
        if (help) {
          help.solved = true; 
          help.answer = generateAnswer.text;
          await help.save();  
        }
      });

      return "done";
    } catch (error) {
      console.error("Inngest helpAiProcess error:", error);
      throw error; 
    }
  }
);
